name: CI

on: [pull_request, push]

jobs:
  install:
    name: Instalando packages
    runs-on: ubuntu-latest
    steps:
      # dar acesso da máquina virtual ao projeto
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Instalando dependencias
        run: npm install

      - name: Testando
        run: npm test

        
